 apiVersion: extensions/v1beta1
 kind: Ingress
 metadata:
   name: node-k8s-demo-ibmcloud
 spec:
   rules:
   - host: 4be30d22-eu-de.lb.appdomain.cloud
     http:
       paths:
       - path: /
         backend:
           serviceName: node-k8s-demo
           servicePort: 8080
