 apiVersion: extensions/v1beta1
 kind: Ingress
 metadata:
   name: node-k8s-demo-ibmcloud2
 spec:
   rules:
   - host: slvpc.eu-de.containers.appdomain.cloud
     http:
       paths:
       - path: /
         backend:
           serviceName: int-http-80
           servicePort: 80
